env_files = [
    { path = "./tools/freyja-build.env", defaults_only = true }
]

[config]
# with workspace support enabled, tasks would be run for each workspace member which we don't want
default_to_workspace = false

# workflows
[tasks.build]
dependencies = ["freyja-depgen", "cargo-build"]

[tasks.test]
dependencies = ["freyja-depgen", "cargo-test"]

[tasks.fmt]
dependencies = ["freyja-depgen", "cargo-fmt"]

[tasks.clippy]
dependencies = ["freyja-depgen", "cargo-clippy"]

[tasks.freyja-ci-build-and-test]
dependencies = ["freyja-depgen", "cargo-build", "cargo-test"]

[tasks.freyja-ci-code-analysis]
dependencies = ["freyja-depgen", "cargo-check", "cargo-clippy", "cargo-fmt-check", "cargo-doctest", "cargo-doc"]

# cargo commands
[tasks.cargo-build]
command = "cargo"
args = ["build"]

[tasks.cargo-test]
command = "cargo"
args = ["test"]

# Note: cargo check should use the --locked option
# Excluding it because of this known issue: https://github.com/mozilla/uniffi-rs/issues/1032
[tasks.cargo-check]
command = "cargo"
args = ["check", "--workspace"]

[tasks.cargo-clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--workspace", "--no-deps", "--", "-D", "warnings"]

[tasks.cargo-fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.cargo-fmt-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.cargo-doctest]
command = "cargo"
args = ["test", "--workspace", "--doc"]

[tasks.cargo-doc]
command = "cargo"
args = ["doc", "--workspace", "--no-deps"]

[tasks.freyja-depgen]
command = "cargo"
args = ["run", "--package", "freyja-depgen"]