@startuml

cloud {
    [Azure Digital Twins]
}

frame "Azure Digital Twins Connector" as azure_cloud_connector {
    [Azure Digital Twins Client]
}

frame "Freyja" as freyja {
    [Emitter] -left-> [Cloud Adapter]
}

[Azure Digital Twins Client] -up---> [Azure Digital Twins]

azure_cloud_connector -down- cloud_connector.proto

[Cloud Adapter] -left--> cloud_connector.proto

' The two hidden arrows below help with spacing between the "Freyja" frame and the "cloud_connector.proto" interface
[Emitter] -[hidden]right--> cloud_connector.proto
[Emitter] -[hidden]up--------> cloud_connector.proto

@enduml
