@startuml
participant "Digital Twin Adapter"
participant "Data Adapter Selector"
participant "Data Adapter"
participant "In-Vehicle Digital Twin Provider"
autonumber

== Selection of a Data Adapter ==

"Digital Twin Adapter"->"Data Adapter Selector": CreateOrUpdateDataAdapter(entity_id, provider_uri, protocol, operation)

alt #LightPink Data Adapter Already Exist
    "Data Adapter Selector"->"Data Adapter Selector": Add entity_id to Data Adapter's local cache
end

alt #Aqua Data Adapter Doesn't Exist
    "Data Adapter Selector"->"Data Adapter": Creates a Data Adapter with provider uri and protocol
    "Data Adapter Selector"->"Data Adapter": Start up
    "Data Adapter Selector"->"Data Adapter Selector": Add entity_id to Data Adapter's local cache
end

"Data Adapter" -> "In-Vehicle Digital Twin Provider": Call get or subscribe for values
"In-Vehicle Digital Twin Provider" -> "Data Adapter": Return values
== Selection of a Data Adapter ==
@enduml