# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "freyja"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
crossbeam = { workspace = true }
env_logger = { workspace = true }
freyja-contracts = { workspace = true }
freyja-common = { workspace = true }
log = { workspace = true }
proc-macros = { workspace = true }
provider-proxy-selector = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }

grpc-provider-proxy-v1 = { path = "../provider_proxies/grpc/v1" }
http-mock-provider-proxy = { path = "../provider_proxies/http_mock_provider_proxy" }
in-memory-mock-provider-proxy = { path = "../provider_proxies/in_memory_mock_provider_proxy" }
managed-subscribe-provider-proxy = { path = "../provider_proxies/managed_subscribe" }
mqtt-provider-proxy = { path = "../provider_proxies/mqtt" }

[dev-dependencies]
# Dependencies for testing
mockall = { workspace = true }
async-trait = { workspace = true }

# Dependencies for examples
in-memory-mock-cloud-adapter = { path = "../cloud_adapters/in_memory_mock_cloud_adapter" }
in-memory-mock-digital-twin-adapter = { path = "../digital_twin_adapters/in_memory_mock_digital_twin_adapter" }
in-memory-mock-mapping-client = { path = "../mapping_clients/in_memory_mock_mapping_client" }
mock-digital-twin-adapter = { path = "../digital_twin_adapters/mock_digital_twin_adapter" }
mock-mapping-service-client = { path = "../mapping_clients/mock_mapping_service_client" }
