# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "in-memory-mock-provider-proxy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
log = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
dts-contracts = { path = "../../contracts"}
proc-macros = { path = "../../proc_macros" }
async-trait = { workspace = true }
crossbeam = { workspace = true }
tower = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
