# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "azure-mqtt-connector"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
paho-mqtt = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
time = { workspace = true }
env_logger = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
futures = { workspace = true }
proc-macros = { path = "../../../proc_macros" }
azure-cloud-connector-proto = { path = "../proto-build/" }

[build-dependencies]
tonic-build = { workspace = true }