# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "grpc-provider-proxy-v1"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = { workspace = true }
crossbeam = { workspace = true }
freyja-common = { workspace = true }
freyja-contracts = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
samples-protobuf-data-access  = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }

[build-dependencies]
freyja-build-common = { workspace = true }