
name: Alex Recommends - language checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.markdown'

jobs:
  alex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    - name: Comment on new PR
      uses: brown-ccv/alex-recommends@v1.2.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message_id: 'alex'
        profanity_sureness: 2