name: Check Spelling
on:
  pull_request:
    branches:
      - main

jobs:
  check_spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install spell
        run: sudo apt-get install -y spell
      - name: Check spelling
        run: |
          EXIT_CODE=0
          
          while IFS= read -r -d '' file; do
            ./tools/check_spelling.sh "$file"
            if [ $? -ne 0 ]; then
              EXIT_CODE=1
            fi
          done < <(find . -name "*.md" -print0)
          
          exit $EXIT_CODE
        shell: bash