name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static_code_analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Install .NET 6.0.119
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.119
          global-json-file: cloud_connectors/azure/digital_twins_connector/global.json
      - name: Cache NuGet dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Build Digital Twins Connector
        run: ./cloud_connectors/azure/digital_twins_connector/build.sh
      - name: Build MQTT Connector's Azure Function
        run: dotnet build cloud_connectors/azure/mqtt_connector/res/azure_function/src/function.csproj
      - name: Digital Twins Connector Tests
        run: dotnet test cloud_connectors/azure/digital_twins_connector/tests/**/*.csproj
      - name: MQTT Connector's Azure Function Tests
        run: dotnet test cloud_connectors/azure/mqtt_connector/tests/**/*.csproj