name: generate plantuml

on: push

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v3
      # with:
      #   ref: ${{ github.event.pull_request.head.ref }}
    # The previous approach to generation has been deprecated because it does not allow a custom committer
    # - name: plantuml
    #   id: plantuml
    #   uses: grassedge/generate-plantuml-action@v1.5
    #   with:
    #     path: .
    #     message: "Render PlantUML files"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: generate plantuml
      run: |
        sudo apt-get install -y plantuml graphviz
        # This uses a slightly off-white background color because #ffffff renders as transparent for some reason
        plantuml -tsvg -SbackgroundColor=fefefe -checkmetadata **/*.puml
      shell: bash
    - name: commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Automated Notice Generation Pipeline
        author_email: ibeji-bot@eclipse.org
        message: Generate PlantUML Diagrams
        pathspec_error_handling: exitAtEnd