name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  FREYJA_MAPPING_CLIENT: in_memory_mock_mapping_client
  FREYJA_DT_ADAPTER: in_memory_mock_digital_twin_adapter
  FREYJA_CLOUD_ADAPTER: in_memory_mock_cloud_adapter

jobs:
  static_code_analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run static code analysis workflow
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: freyja-ci-static-code-analysis

  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build and Test
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: freyja-ci-build-and-test