@startuml

cloud {
    [Mapping Service] as cloudMappingSvc
}

cloud {
    [Cloud Digital Twin]
}

package "Vehicle" {
    frame "Freyja" {
        [Cartographer]
        interface "Digital Twin Adapter"
        interface "Mapping Adapter"
        [Emitter]
        interface "Cloud Adapter"
        database "Signal Store"
        [Data Adapter Selector]
        node "Data Adapters" {
            [Data Adapter] as data_adapter
        }
    }

    [Chariott]

    frame "Ibeji" {
        [In-Vehicle Digital Twin Service] as ivdts
        node "Digital Twin Providers" {
            [Digital Twin Provider] as provider
        }
    }

    [Cloud Connector]
    [Mapping Service] as ivMappingSvc
}

[Emitter] -u-> [Cloud Adapter] : Emit Data
[Cloud Adapter] -u-> [Cloud Connector] : Emit Data
[Cartographer] <-u-> [Mapping Adapter] : Get Mapping
[Mapping Adapter] <-[norank]-> [ivMappingSvc] : Get Mapping
[ivMappingSvc] <.u.> [cloudMappingSvc]
[Cloud Connector] -u-> [Cloud Digital Twin]
[Cartographer] -d-> [Digital Twin Adapter]
[Digital Twin Adapter] .d.> [Chariott] : Discover Ibeji (optional)
[Digital Twin Adapter] -d-> [ivdts] : Discover Providers
[Cartographer] -u-> [Signal Store] : Track Signals
[Cartographer] -r-> [Data Adapter Selector] : Register Adapters
[Data Adapter Selector] -r-> [data_adapter] : Register Adapters
[data_adapter] <-d-> [provider] : Collect data
[data_adapter] -u-> [Signal Store] : Update signal values
[Emitter] <-l- [Signal Store] : Retrieve data
[Chariott] <-r-> [ivdts]
[ivdts] <-r-> [provider]

@enduml
