@startuml
participant "Freyja Cartographer"
participant "Mapping Service"
autonumber

== Freyja Communication with Mapping Service ==

"Freyja Cartographer"->"Mapping Service": Query for mapping metadata
"Mapping Service"->"Freyja Cartographer": Respond with metadata

alt #LightBlue Metadata specifies a new mapping is available
    "Freyja Cartographer"->"Mapping Service": Query for mapping
    "Mapping Service"->"Freyja Cartographer" : Respond with mapping
end

== Freyja Communication with Mapping Service ==
@enduml

